spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/business_registration_number?zeroDateTimeBehavior=convertToNull&autoReconnection=true&autoReconnectForPools=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: yshss1
    password: test1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  secret: javainuse